#define IDC_MYICON                      2
#define IDD_CUSTOMWELCOME95_DIALOG      102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_CUSTOMWELCOME95             107
#define IDC_CUSTOMWELCOME95             109
#define IDR_MAINFRAME                   128
#define IDB_BITMAP1                     129
#define IDB_WELCOME                     129
#define IDD_WELCOMEBOX                  130
#define IDC_HIDDENBUTTON                1000
#define IDC_STATIC                      -1
